name: billing
description: "A new Flutter project."
version: 0.0.1
homepage: https://www.linkfive.io

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  linkfive_purchases: 4.0.0-1.beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
