name: pencalendar
description: "Stift Flutter App: The Calendar for Tablets"
publish_to: 'none'
homepage: 'https://thiele.dev'
version: 1.2.2+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  intl: ^0.18.1
  flutter_riverpod: ^2.4.9
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.4
  cloud_firestore: ^4.13.1
  flutter_colorpicker: ^1.0.3
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  in_app_review: ^2.0.8
  country_codes: ^2.2.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  collection: ^1.17.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.2.0+1
  flutter_shaders: ^0.1.2
  rate_my_app: ^2.0.0
  responsive_spacing: ^1.1.0
  share_plus: 7.2.1
  flutter_slidable: ^3.0.1
  design_system:
    path: packages/design_system/
  localizations:
    path: packages/localizations
  billing:
    path: packages/billing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  shaders:
    - assets/shader/splash-small.frag
    - assets/shader/kishimisu.frag
    - assets/shader/ui-glitch.frag
    - assets/shader/jwibullori.frag
    - assets/shader/fractalcineshader.frag

flutter_launcher_icons:
  image_path_android: "assets/logo/appicon.png"
  image_path_ios: "assets/logo/appicon_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#2C304D"
  adaptive_icon_foreground: "assets/logo/appicon_fg.png"
  min_sdk_android: 23
  remove_alpha_ios: true