name: pencalendar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+8

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^4.2.8
  intl: ^0.17.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.0-dev.9
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.5
  flutter_colorpicker: ^1.0.3
  another_xlider: ^1.1.2
  font_awesome_flutter: ^10.3.0
  firebase_app_check: ^0.1.1+5
  event_bus: ^2.0.0
  url_launcher: ^6.1.7
  in_app_review: ^2.0.6
  country_codes: ^2.2.0
  http: ^0.13.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path_android: "assets/logo/appicon.png"
  image_path_ios: "assets/logo/appicon_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FAFEF2"
  adaptive_icon_foreground: "assets/logo/appicon_fg.png"
  min_sdk_android: 23